server.port=1009

# ??? ??? ?? ???  ???? 8K
#????
#oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# 19c
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/orcl
# 11c
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=bdh
spring.datasource.password=1234
## jpa
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#Hibernate? DB? ??????.
spring.jpa.show-sql=true
#??, ???????? ?????????????. validate create update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.database=oracle
# 1. ?? ????? ?? (?? ???)
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
# 2. ?????? 6 ???? 11g ???(ROWNUM)? ???? ?? ??
spring.jpa.properties.hibernate.dialect.oracle.version=11


